export const creditCardActions = {
  POST_CARD_INFO: 'POST_CARD_INFO',
  SAVE_CARD_LOCAL: 'SAVE_CARD_LOCAL',
  SAVE_CARD_RESULT: 'SAVE_CARD_RESULT',
  SET_API_ERROR_MESSAGE: 'SET_API_ERROR_MESSAGE'
};

export const generalActions = {
  SET_APP_LOADING : 'SET_APP_LOADING'
};